name: "$(SourceBranchName)+$(BuildID)"

pool:
  name: 'AWS-ECS'

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml
extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: {% raw %}${{ variables.service_name }}{% endraw %}
    short_service_name: {% raw %}${{ variables.short_service_name }}{% endraw %}
