name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "{{ PIPELINE_NAME_PREFIX }}-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: {% raw %}${{ variables.service_name }} {% endraw %}
    short_service_name: {% raw %}${{ variables.short_service_name }} {% endraw %}
    service_base_path: {% raw %}${{ variables.service_base_path }} {% endraw %}
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: ./templates/run-smoke-tests.yml
      - environment: internal-qa
        post_deploy:
          - template: ./templates/run-smoke-tests.yml
      - environment: internal-qa-sandbox
        proxy_path: sandbox
        post_deploy:
          - template: ./templates/run-smoke-tests.yml
    # (App subscription make sense for most sandbox implementations)
      - environment: sandbox
        proxy_path: sandbox
        post_deploy:
          - template: ./templates/run-smoke-tests.yml
    # Enable int environment when ready by uncommenting:
    #   - environment: int
    #     depends_on:
    #       - internal_qa
    #       - internal_qa_sandbox
    #     post_deploy:
    #       - template: ./templates/run-smoke-tests.yml
