name: "$(SourceBranchName)+$(BuildID)"

trigger: none

pr:
  branches:
    include:
      - master

resources:
  pipelines:
  - pipeline: {{ config.meta.canonical_name }}
    source: "Identity-Service-Build"

parameters:
  - name : artifactBranch
    displayName: Artifact Branch (e.g. feature/myfeature or v1.0.0-alpha)
    type: string
    default: $(Build.SourceBranch)
  - name : artifactBuildId
    displayName: Artifact Build Id (e.g. run Id for the build to download). Overrides Artifact Branch if not "latest".
    type: string
    default: latest

variables:
  SERVICE_NAME: {{ config.meta.canonical_name }}
  SERVICE_BASE_PATH: {{ config.base_path }}
  VARIABLES_KVM: "{{ config.meta.short_name }}-variables"
  ENCRYPTED_VARIABLES_KVM: "{{ config.meta.short_name }}-variables-encrypted"
  IDENTITY_TARGET_SERVER: identity-server
  FORCE_SANDBOX: false
  NAMESPACE: from_branchname

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: DeployInternalDev
    displayName: internal-dev
    variables:
    - group: apigee-nonprod
    - group: env-internal-dev
    jobs:
      - deployment: DeployService
        displayName: Deploy Service
        environment: 'internal-dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/download-build-artifact.yml
                  parameters:
                    serviceName: $(SERVICE_NAME)
                    artifactBuildId: {% raw %}${{ parameters.artifactBuildId }}{% endraw %}
                    artifactBranch: {% raw %}${{ parameters.artifactBranch }}{% endraw %}
                    pipelineAlias: {{ config.meta.canonical_name }}
                - template: templates/identity-service-templating.yml
                - template: templates/deploy-namespaced-service.yml
