name: "$(SourceBranchName)+$(BuildID)"

# Prevents building every commit or on PR
trigger: none
pr: none

# Consume an artifact from the build pipeline as soon as it becomes available.
resources:
  pipelines:
    - pipeline: "{{ config.meta.canonical_name }}"
      source: "{{ config.meta.pipeline_name_prefix }}-Build"
      trigger:
        branches:
          include:
            - refs/tags/v*
  repositories:
    - repository: templates
      type: github
      name: NHSDigital/api-management-utils
      ref: 'refs/heads/APM-1120-Template-Pipelines'
      endpoint: NHSDigital
      
variables:
  SERVICE_NAME: {{ config.meta.canonical_name }}
  SERVICE_BASE_PATH: {{ config.base_path }}

parameters:
  - name : artifactBranch
    displayName: Artifact Branch (e.g. feature/myfeature or v1.0.0-alpha)
    type: string
    default: $(Build.SourceBranch)
  - name : artifactBuildId
    displayName: Artifact Build Id (e.g. run Id for the build to download). Overrides Artifact Branch if not "latest".
    type: string
    default: latest

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployInternalDev
  displayName: internal-dev
  variables:
  - group: apigee-nonprod
  - group: env-internal-dev
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'internal-dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: az/templates/download-build-artifact.yml@templates
                parameters:
                  serviceName: $(SERVICE_NAME)
                  artifactBuildId: {{ '${{ parameters.artifactBuildId }}' }}
                  artifactBranch: {{ '${{ parameters.artifactBranch }}' }}
                  pipelineAlias: {{ config.meta.canonical_name }}
              - template: az/templates/deploy-service.yml@templates

- stage: DeployInternalQA
  displayName: internal-qa
  dependsOn: DeployInternalDev
  variables:
    - group: apigee-nonprod
    - group: env-internal-qa
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'internal-qa'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: az/templates/download-build-artifact.yml@templates
                parameters:
                  serviceName: $(SERVICE_NAME)
                  artifactBuildId: {{ '${{ parameters.artifactBuildId }}' }}
                  artifactBranch: {{ '${{ parameters.artifactBranch }}' }}
                  pipelineAlias: {{ config.meta.canonical_name }}
              - template: az/templates/deploy-service.yml@templates

- stage: DeployInternalQASandbox
  displayName: internal-qa-sandbox
  dependsOn: DeployInternalDev
  variables:
    - group: apigee-nonprod
    - group: env-internal-qa-sandbox
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'internal-qa-sandbox'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: az/templates/download-build-artifact.yml@templates
                parameters:
                  serviceName: $(SERVICE_NAME)
                  artifactBuildId: {{ '${{ parameters.artifactBuildId }}' }}
                  artifactBranch: {{ '${{ parameters.artifactBranch }}' }}
                  pipelineAlias: {{ config.meta.canonical_name }}
              - template: az/templates/deploy-service.yml@templates

- stage: DeployInternalPortal
  displayName: internal-portal
  dependsOn: DeployInternalDev
  variables:
    - group: apigee-nonprod
    - group: env-internal-portal
  jobs:
    - deployment: DeploySpecs
      displayName: Deploy Specs
      environment: 'internal-portal'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: az/templates/download-build-artifact.yml@templates
                parameters:
                  serviceName: $(SERVICE_NAME)
                  artifactBuildId: {{ '${{ parameters.artifactBuildId }}' }}
                  artifactBranch: {{ '${{ parameters.artifactBranch }}' }}
                  pipelineAlias: {{ config.meta.canonical_name }}
              - template: az/templates/deploy-specs.yml@templates

- stage: DeployRef
  displayName: ref
  dependsOn: 
    - DeployInternalQA
    - DeployInternalQASandbox
  variables:
    - group: apigee-nonprod
    - group: env-ref
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'ref'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: az/templates/download-build-artifact.yml@templates
                parameters:
                  serviceName: $(SERVICE_NAME)
                  artifactBuildId: {{ '${{ parameters.artifactBuildId }}' }}
                  artifactBranch: {{ '${{ parameters.artifactBranch }}' }}
                  pipelineAlias: {{ config.meta.canonical_name }}
              - template: az/templates/deploy-service.yml@templates

- stage: DeployDev
  displayName: dev
  dependsOn: 
    - DeployRef
  variables:
    - group: apigee-prod
    - group: env-dev
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: az/templates/download-build-artifact.yml@templates
                parameters:
                  serviceName: $(SERVICE_NAME)
                  artifactBuildId: {{ '${{ parameters.artifactBuildId }}' }}
                  artifactBranch: {{ '${{ parameters.artifactBranch }}' }}
                  pipelineAlias: {{ config.meta.canonical_name }}
              - template: az/templates/deploy-service.yml@templates

- stage: DeployProd
  displayName: prod
  dependsOn: 
    - DeployRef
  variables:
    - group: apigee-prod
    - group: env-prod
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'prod'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: az/templates/download-build-artifact.yml@templates
                parameters:
                  serviceName: $(SERVICE_NAME)
                  artifactBuildId: {{ '${{ parameters.artifactBuildId }}' }}
                  artifactBranch: {{ '${{ parameters.artifactBranch }}' }}
                  pipelineAlias: {{ config.meta.canonical_name }}
              - template: az/templates/deploy-service.yml@templates

- stage: DeploySandbox
  displayName: sandbox
  dependsOn: 
    - DeployRef
  variables:
    - group: apigee-prod
    - group: env-sandbox
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'sandbox'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: az/templates/download-build-artifact.yml@templates
                parameters:
                  serviceName: $(SERVICE_NAME)
                  artifactBuildId: {{ '${{ parameters.artifactBuildId }}' }}
                  artifactBranch: {{ '${{ parameters.artifactBranch }}' }}
                  pipelineAlias: {{ config.meta.canonical_name }}
              - template: az/templates/deploy-service.yml@templates

- stage: DeployInt
  displayName: int
  dependsOn: 
    - DeployRef
  variables:
    - group: apigee-prod
    - group: env-int
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'int'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: az/templates/download-build-artifact.yml@templates
                parameters:
                  serviceName: $(SERVICE_NAME)
                  artifactBuildId: {{ '${{ parameters.artifactBuildId }}' }}
                  artifactBranch: {{ '${{ parameters.artifactBranch }}' }}
                  pipelineAlias: {{ config.meta.canonical_name }}
              - template: az/templates/deploy-service.yml@templates

- stage: DeployPortal
  displayName: portal
  dependsOn:
    - DeployProd
    - DeploySandbox
  variables:
    - group: apigee-prod
    - group: env-portal
  jobs:
    - deployment: DeploySpecs
      displayName: Deploy Specs
      condition: false
      environment: 'portal'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: az/templates/download-build-artifact.yml@templates
                parameters:
                  serviceName: $(SERVICE_NAME)
                  artifactBuildId: {{ '${{ parameters.artifactBuildId }}' }}
                  artifactBranch: {{ '${{ parameters.artifactBranch }}' }}
                  pipelineAlias: {{ config.meta.canonical_name }}
              - template: az/templates/deploy-specs.yml@templates
