name: "$(SourceBranchName)+$(BuildID)"

# Prevents building every commit or on PR
trigger: none
pr: none

# Consume an artifact from the build pipeline as soon as it becomes available.
resources:
  pipelines:
    - pipeline: "{{ config.meta.canonical_name }}"
      source: "{{ config.meta.pipeline_name_prefix }}-Build"
      trigger:
        branches:
          exclude:
            - 'refs/tags/v*'
            - 'master'
  repositories:
    - repository: templates
      type: github
      name: NHSDigital/api-management-utils
      ref: 'refs/heads/APM-1120-Template-Pipelines'
      endpoint: NHSDigital

parameters:
  - name : artifactBranch
    displayName: Artifact Branch (e.g. feature/myfeature or v1.0.0-alpha)
    type: string
    default: $(Build.SourceBranch)
  - name : artifactBuildId
    displayName: Artifact Build Id (e.g. run Id for the build to download). Overrides Artifact Branch if not "latest".
    type: string
    default: latest

variables:
  SERVICE_NAME: {{ config.meta.canonical_name }}
  SERVICE_BASE_PATH: {{ config.base_path }}
  FORCE_SANDBOX: false
  NAMESPACE: from_branchname

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: DeployInternalDev
    displayName: internal-dev
    variables:
    - group: apigee-nonprod
    - group: env-internal-dev
    jobs:
      - deployment: DeployService
        displayName: Deploy Service
        environment: 'internal-dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: az/templates/download-build-artifact.yml@templates
                  parameters:
                    serviceName: $(SERVICE_NAME)
                    artifactBuildId: {{ '${{ parameters.artifactBuildId }}' }}
                    artifactBranch: {{ '${{ parameters.artifactBranch }}' }}
                    pipelineAlias: {{ config.meta.canonical_name }}
                - template: az/templates/deploy-namespaced-service.yml@templates
