variables:
  - group: status-endpoint
  - name: service_name
    value: {{ SERVICE_NAME }}
  - name: short_service_name
    value: {{ SHORT_SERVICE_NAME }}
  - name: service_base_path
    value: {{ SERVICE_BASE_PATH }}
