# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the Personal Demographics Service (PDS) API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: "3.0.0"
info:
  version: "{VERSION}"
  title: example template Service (FHIR) API
  description: Overview

  contact:
    name: example template FHIR API Support
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net

servers:
  - url: 'https://sandbox.api.service.nhs.uk/example-template'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/example-template'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/example-template'
    description: 'Production environment.'

tags:
  - name: patients

paths:
  /users:
    get:
      summary: Returns a list of users.
      operationId: search-patient
      externalDocs:
        description: ODS codes and documentation.
        url: https://fhir.nhs.uk/Id/ods-organization-code
      description: Optional extended description in CommonMark or HTML.
      tags:
        - patients
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string