# This is an OpenAPI Specification (https://swagger.io/specification/)
# for {{ SERVICE_NAME }} owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: '{{ SERVICE_NAME }}'
  version: 'Computed and injected at build time by `scripts/set_version.py`'
  description: |
    ## Overview
    Add a fully fledged description here with markdown syntax.
    ## Who can use this API
    ## Related APIs
    ## API status and roadmap
    ## Service level
    ## Technology
    ## Network access
    ## Security and authorisation
    ## Environments and testing
    ## Onboarding
  contact:
    name: '{{ SERVICE_NAME }} API Support'
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/{{ SERVICE_BASE_PATH }}'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/{{ SERVICE_BASE_PATH }}'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/{{ SERVICE_BASE_PATH }}'
    description: Production environment.
paths: {}
