# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the Personal Demographics Service (PDS) API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: "3.0.0"
info:
  version: "{VERSION}"
  title: Template API
  description: |
    ## Overview
    TODO
    
    You can:
    * TODO

    You cannot currently use this API to:
    * TODO
    
    You can access the following data:
    * TODO

    ## Related APIs
    TODO
    
    ## API status and roadmap
    TODO
    
    The following items are on our roadmap, in rough priority order:
    - TODO
    
    We are extremely keen to receive feedback on the API during alpha and beta,
    for example if there are data fields missing that you think you need.
    Please [get in touch](/help-and-support) with any comments or suggestions.

    ## Technology
    This API is [RESTful](/introduction-to-apis#basic-rest).

    It also conforms to the [FHIR](/introduction-to-apis#fhir) global standard for health care data exchange.
    Specifically, it is aligned with [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core), which is built on FHIR Release 4.

    You don’t need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules.
    In particular:
    - resource names are capitalised and singular, for example the `/Patient` not `/patients`
    - array names are singular, for example `line` not `lines` for address lines
    - data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an `extension` object

    This API is available on the Internet, although access using NHS smartcards (see below)
    currently requires a connection to the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).

    ## Authorisation
    TODO
    
    ## Testing
    You can test this API in:
    * our [sandbox environment](/testing#sandbox-testing) for initial developer testing
    * our [integration test environment](/testing#integration-testing) for formal integration testing (coming soon)

    Our sandbox environment is a very basic simulation of the live service. It only covers a limited set of scenarios and is stateless, so does not actually persist any updates.

    For more details on sandbox testing, or to try out the sandbox using our "Try this API" feature, see the documentation for each endpoint.

    Alternatively, you can try out the sandbox using our Postman collection:

    [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/2871d49488699f3f5a67)

    ## Assurance
    We are hoping to make the assurance process as lightweight and as self-service as possible.

    More details to follow.

    ## Endpoints
    To see details for specific endpoints, select from the list on the left hand side of the page:
    * `GET /example` - request exmaple response
  contact:
    name: Template API Support
    url: 'https://tbc.api.nhs.net'
    email: tbc-api-support@nhs.net
servers:
  - url: 'https://emea-demo8-test.apigee.net/TODO sandbox endpoint'
    description: Sandbox service.
tags:
  - name: example-route
paths:
  /example:
    get:
      tags:
        - example-route
      summary: Example endpoint
      operationId: example
      description: The example endpoint to retrieve an example response.
      paramaters:
        - name: is_successful
          description: Toggle for successful response
          example: true
          in: query
          required: true
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: A successful token exchange request
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    description: Example data returned from the API
                    example: Example data
                  timestamp:
                    type: string
                    description: Time the search was performed.
                    format: datetime
                    example: '2019-12-25T12:00:00+00:00'
        '400':
          description: Invalid search paramaters supplied.
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: Example error code from template api
                    example: '400'
